use_frameworks!

platform :ios, '10.0'

target 'HuntingZombiesTool_Example' do
  pod 'HuntingZombiesTool', :path => '../'

  target 'HuntingZombiesTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
